name: Build & Deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Extract branch name
        id: extract_branch
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/harryli0088/nextjs-mongo-auth0/${{ env.BRANCH_NAME }}:latest
            ghcr.io/harryli0088/nextjs-mongo-auth0/${{ env.BRANCH_NAME }}:${{ github.sha }}

      - name: Trigger Watchtower webhook
        env:
          WATCHTOWER_BEARER_TOKEN: ${{ secrets.WATCHTOWER_BEARER_TOKEN }}
          WATCHTOWER_URL: ${{ secrets.WATCHTOWER_URL }}
        run: |
          curl -H "Authorization: Bearer $WATCHTOWER_BEARER_TOKEN" $WATCHTOWER_URL